font=monospace:size=16

[colors]
background=000000  # This sets the background color to black
foreground=ffffff  # This sets the text color to white (optional)

[key-bindings]
#clipboard-copy=Control+c XF86Copy
#clipboard-paste=Control+v XF86Paste
